custom_cursor_colors = true

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001w"
key = "S"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001q"
key = "D"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001x"
key = "W"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00011"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00012"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00013"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00014"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00015"
key = "Key5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00016"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00017"
key = "Key7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00018"
key = "Key8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00019"
key = "Key9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001k"
key = "J"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001j"
key = "K"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[general]
live_config_reload = true

[terminal]

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[bell]
animation = "EaseOutExpo"
color = "0xfab795"
duration = 4

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x5b5858"
blue = "0x3fc4de"
cyan = "0x6be4e6"
green = "0x3fdaa4"
magenta = "0xf075b5"
red = "0xec6a88"
white = "0xd5d8da"
yellow = "0xfbc3a7"

[colors.cursor]
cursor = "0x29d398"

[colors.normal]
black = "0x16161c"
blue = "0x26bbd9"
cyan = "0x59e1e3"
green = "0x29d398"
magenta = "0xee64ac"
red = "0xe95678"
white = "0xd5d8da"
yellow = "0xfab795"

[colors.primary]
background = "0x1c1e26"
foreground = "0xe0e0e0"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Off"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 15.5

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Light Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Light"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[mouse.double_click]
threshold = 300

[mouse.hints]
modifiers = "Control"

[mouse.hints.launcher]
program = "open"

[mouse.triple_click]
threshold = 300

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',â”‚`|:"' ()[]{}<>'''

[terminal.shell]
args = ["new-session", "-A", "-D", "-s", "main"]
program = "/usr/bin/tmux"

[window]
decorations = "Full"
dynamic_padding = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 130
lines = 45

[window.padding]
x = 5
y = 5

[keyboard]
